@echo off
cd /d E:/projectHome/media-cli/dola/cli
set LOG=E:/projectHome/media-cli/dola/cli/batch-submit.log
echo === jiejin-v2-shot02-001 === >> "%LOG%"
node src/cli.js video submit --prompt "Two rounded chat speech bubbles gently bobbing as they face each other, a small question mark floating and rotating slowly between them, subtle breathing motion, flat 3D clay render style, soft studio lighting, no text, no letters" --duration 5 --aspect-ratio 16:9 --request-id jiejin-v2-shot02-001 --file "E:/projectHome/media-cli/chatgpt/cli/downloads/jiejin-v2/shot-02.png" --json >> "%LOG%" 2>&1
echo === jiejin-v2-shot03-001 === >> "%LOG%"
node src/cli.js video submit --prompt "An open book with a small padlock icon standing on its pages, a magnifying glass hovering and slowly gliding above the page, gentle warm light, subtle floating motion, flat 3D clay render, soft studio light, no text, no letters" --duration 5 --aspect-ratio 16:9 --request-id jiejin-v2-shot03-001 --file "E:/projectHome/media-cli/chatgpt/cli/downloads/jiejin-v2/shot-03.png" --json >> "%LOG%" 2>&1
echo === jiejin-v2-shot04-001 === >> "%LOG%"
node src/cli.js video submit --prompt "A rocket slowly lifting off from a launch pad while a bundle of stock certificate documents wrapped in a thick metal chain rests beside it, gentle smoke puffs, camera slowly rising, flat 3D clay render, soft studio light, no text, no letters" --duration 5 --aspect-ratio 16:9 --request-id jiejin-v2-shot04-001 --file "E:/projectHome/media-cli/chatgpt/cli/downloads/jiejin-v2/shot-04.png" --json >> "%LOG%" 2>&1
echo === jiejin-v2-shot06-001 === >> "%LOG%"
node src/cli.js video submit --prompt "A single padlock gently rotating with three small question marks floating and orbiting slowly around it, soft studio lighting, subtle floating motion, flat 3D clay render, no text, no letters" --duration 5 --aspect-ratio 16:9 --request-id jiejin-v2-shot06-001 --file "E:/projectHome/media-cli/chatgpt/cli/downloads/jiejin-v2/shot-06.png" --json >> "%LOG%" 2>&1
echo === jiejin-v2-shot07-001 === >> "%LOG%"
node src/cli.js video submit --prompt "Split composition: a small rocket gently rising upward on the left while a hand drops a coin into a money bag on the right, slow motion, gentle floating, flat 3D clay render style, soft studio lighting, no text, no letters" --duration 5 --aspect-ratio 16:9 --request-id jiejin-v2-shot07-001 --file "E:/projectHome/media-cli/chatgpt/cli/downloads/jiejin-v2/shot-07.png" --json >> "%LOG%" 2>&1
echo === jiejin-v2-shot08-001 === >> "%LOG%"
node src/cli.js video submit --prompt "An hourglass with sand trickling through and a stock price line falling through it in slow motion, grains of sand sparkling, subtle camera push-in, flat 3D clay render, soft studio light, no text, no letters" --duration 5 --aspect-ratio 16:9 --request-id jiejin-v2-shot08-001 --file "E:/projectHome/media-cli/chatgpt/cli/downloads/jiejin-v2/shot-08.png" --json >> "%LOG%" 2>&1
echo === jiejin-v2-shot09-001 === >> "%LOG%"
node src/cli.js video submit --prompt "A large stylized brain with a radar sweep beam circling around it, a small calculator beside it with numbers subtly shifting, gentle pulsing glow, flat 3D clay render, soft studio light, no text, no letters" --duration 5 --aspect-ratio 16:9 --request-id jiejin-v2-shot09-001 --file "E:/projectHome/media-cli/chatgpt/cli/downloads/jiejin-v2/shot-09.png" --json >> "%LOG%" 2>&1
echo === jiejin-v2-shot10-001 === >> "%LOG%"
node src/cli.js video submit --prompt "Two stacks of trading chips on a platform, the right stack slowly growing taller until it is twice the height of the left stack, two arrows subtly pulsing to show the doubling, flat 3D clay render, soft studio light, no text, no letters" --duration 5 --aspect-ratio 16:9 --request-id jiejin-v2-shot10-001 --file "E:/projectHome/media-cli/chatgpt/cli/downloads/jiejin-v2/shot-10.png" --json >> "%LOG%" 2>&1
echo === jiejin-v2-shot11-001 === >> "%LOG%"
node src/cli.js video submit --prompt "A cute vegetable market stall with a basket of fresh vegetables, a second identical stall fading in right next to it, a small price tag floating gently downward, flat 3D clay render, soft studio light, no text, no letters" --duration 5 --aspect-ratio 16:9 --request-id jiejin-v2-shot11-001 --file "E:/projectHome/media-cli/chatgpt/cli/downloads/jiejin-v2/shot-11.png" --json >> "%LOG%" 2>&1
echo === jiejin-v2-shot12-001 === >> "%LOG%"
node src/cli.js video submit --prompt "A stock price line chart dropping steeply from a high point on the left to a low point on the right, two round marker dots pulsing on the line, a subtle downward arrow, flat 3D clay render, soft studio light, no text, no letters" --duration 5 --aspect-ratio 16:9 --request-id jiejin-v2-shot12-001 --file "E:/projectHome/media-cli/chatgpt/cli/downloads/jiejin-v2/shot-12.png" --json >> "%LOG%" 2>&1
echo === jiejin-v2-shot13-001 === >> "%LOG%"
node src/cli.js video submit --prompt "A financial report folder with a red X mark over it, next to it a calendar page with a small padlock icon, gentle camera orbit, subtle shadows shifting, flat 3D clay render, soft studio light, no text, no letters" --duration 5 --aspect-ratio 16:9 --request-id jiejin-v2-shot13-001 --file "E:/projectHome/media-cli/chatgpt/cli/downloads/jiejin-v2/shot-13.png" --json >> "%LOG%" 2>&1
echo === jiejin-v2-shot14-001 === >> "%LOG%"
node src/cli.js video submit --prompt "A balance scale slowly tipping toward the sunny side, a small dark cloud dissipating on one side as a small sun brightens on the other, gentle motion, flat 3D clay render, soft studio light, no text, no letters" --duration 5 --aspect-ratio 16:9 --request-id jiejin-v2-shot14-001 --file "E:/projectHome/media-cli/chatgpt/cli/downloads/jiejin-v2/shot-14.png" --json >> "%LOG%" 2>&1
echo === jiejin-v2-shot15-001 === >> "%LOG%"
node src/cli.js video submit --prompt "A wall calendar page with a highlighted date gently swaying, next to it a flat calm stock price line that barely moves with small waves of selling pressure already absorbed, flat 3D clay render, soft studio light, no text, no letters" --duration 5 --aspect-ratio 16:9 --request-id jiejin-v2-shot15-001 --file "E:/projectHome/media-cli/chatgpt/cli/downloads/jiejin-v2/shot-15.png" --json >> "%LOG%" 2>&1
echo === jiejin-v2-shot16-001 === >> "%LOG%"
node src/cli.js video submit --prompt "Split composition: on the left two open hands catching falling coins, on the right coins falling into an empty dark space below, coins sparkling in slow motion, flat 3D clay render, soft studio light, no text, no letters" --duration 5 --aspect-ratio 16:9 --request-id jiejin-v2-shot16-001 --file "E:/projectHome/media-cli/chatgpt/cli/downloads/jiejin-v2/shot-16.png" --json >> "%LOG%" 2>&1
echo === jiejin-v2-shot17-001 === >> "%LOG%"
node src/cli.js video submit --prompt "Three rounded cards connected in a horizontal flow, a radar icon pulsing on the first card, a downward arrow gliding on the second card, a calm flat line on the third card, small arrows flowing between the cards, flat 3D clay render, soft studio light, no text, no letters" --duration 5 --aspect-ratio 16:9 --request-id jiejin-v2-shot17-001 --file "E:/projectHome/media-cli/chatgpt/cli/downloads/jiejin-v2/shot-17.png" --json >> "%LOG%" 2>&1
echo === jiejin-v2-shot18-001 === >> "%LOG%"
node src/cli.js video submit --prompt "A padlock slowly transforming into an open hand holding a stock certificate, gentle glow and sparkles, optimistic mood, smooth morph, flat 3D clay render, soft studio light, no text, no letters" --duration 5 --aspect-ratio 16:9 --request-id jiejin-v2-shot18-001 --file "E:/projectHome/media-cli/chatgpt/cli/downloads/jiejin-v2/shot-18.png" --json >> "%LOG%" 2>&1
echo BATCH-DONE >> "%LOG%"
